project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  #title: "Sina Azadnajafabad, MD, MPH"
  site-url: https://sina-azad.github.io/
  favicon: media/Logo 1.png
  google-analytics: 
    tracking-id: "G-5W8GMD5CSV"
    anonymize-ip: true
  navbar:
    logo: media/Logo 1.png
    logo-alt: "My initials has made this logo, SA"
    
    left: # navigation bar location: accepts right/left/center
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      # - href: presentations.qmd
      #   text: Presentations
      - href: news.qmd
        text: News
        
    right: 
      - text: "<i class='fa-brands fa-linkedin'></i>"
        href: https://www.linkedin.com/in/sinaazadnajafabad/
        target: _blank
      - text: "<i class='fa-brands fa-orcid'></i>"
        href: https://orcid.org/0000-0003-0105-3801
        target: _blank
      - text: "<i class='fa-brands fa-google-scholar'></i>"
        href: https://scholar.google.com/citations?hl=en&user=OqOPJOEAAAAJ&view_op=list_works&sortby=pubdate&inst=2230987035966559800
        target: _blank
      - text: "<i class='fa-brands fa-researchgate'></i>"
        href: https://www.researchgate.net/profile/Sina-Azadnajafabad
        target: _blank
      - text: "<i class='fa-brands fa-github'></i>"
        href: https://github.com/sina-azad
        target: _blank
      - text: "<i class='fa-brands fa-x-twitter'></i>"
        href: https://x.com/SinaAzadMD
        target: _blank
      - text: "<i class='fa-brands fa-bluesky'></i>"
        href: https://bsky.app/profile/sinaazadmd.bsky.social
        target: _blank
      - text: "<i class='fa-solid fa-envelope'></i>"
        href: mailto:sina.azad.u@gmail.com

  page-footer: 
    left: © 2025 Sina Azadnajafabad
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/){target=_blank}



format:
  html:
    theme: 
      - flatly
      - mystyles.scss
    mainfont: Nunito
    toc: true
    page-layout: full
    include-after-body: 
      - altmetric-script.html # Include the Altmetric JavaScript Globally
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

editor: source

