project:
  type: website
  output-dir: docs

website:
  title: "Sina Azadnajafabad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      light: simplex      
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

