project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: false

execute: 
  freeze: auto

website:
  # title: "Sina Azad"
  site-url: https://sinaazad.com/
  favicon: media/1_Home/favicon_SA_3.png
  google-analytics: 
    tracking-id: "G-5W8GMD5CSV"
    anonymize-ip: true
  navbar:
    logo: media/1_Home/favicon_SA_3.png
    logo-alt: "My initials has made this logo, SA"
    collapse: true
    pinned: true
    
    left: # navigation bar location: accepts right/left/center
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: news.qmd
        text: News
      - href: resources.qmd
        text: Resources
        
    right: 
      - text: "{{< fa brands linkedin >}}"
        href: https://www.linkedin.com/in/sinaazadnajafabad/
        target: _blank
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0003-0105-3801
        target: _blank
      - text: "{{< fa brands google-scholar >}}"
        href: https://scholar.google.com/citations?hl=en&user=OqOPJOEAAAAJ&view_op=list_works&sortby=pubdate&inst=2230987035966559800
        target: _blank
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Sina-Azadnajafabad
        target: _blank
      - text: "{{< fa brands github >}}"
        href: https://github.com/sina-azad
        target: _blank
      - text: "{{< fa brands x-twitter >}}"
        href: https://x.com/SinaAzadMD
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/sinaazadmd.bsky.social
        target: _blank
      - text: "{{< fa envelope >}}"
        href: mailto:sina.azad.u@gmail.com

  page-footer: 
    center: © 2025 Sina Azadnajafabad<br> Website built with [{{< iconify simple-icons:quarto >}}](https://quarto.org/){target=_blank}, [{{< fa brands r-project >}}](https://www.r-project.org/about.html){target=_blank} and [{{< fa brands github >}}](https://github.com/){target=_blank}


format:
  html:
    theme: 
      - mystyles.scss
    mainfont: Roboto
    toc: true
    page-layout: full
    include-after-body: 
      - altmetric-script.html # Include the Altmetric JavaScript Globally
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

editor: source

