project:
  type: website
  output-dir: docs

website:
  title: "Sina Azadnajafabad"
  site-url: https://sina-azad.github.io/
  favicon: media/Logo 1.png
  google-analytics: 
    tracking-id: "G-5W8GMD5CSV"
    anonymize-ip: false
  navbar:
    logo: media/Logo 1.png
    logo-alt: "Alt text for logo"
    
    right: # navigation bar location: accepts right/left/center
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: presentations.qmd
        text: Presentations & Talks
      - href: news.qmd
        text: News        
      - href: mailto:sina.azad.u@gmail.com
        text: Contact Me
        
  page-footer: 
    left: © 2024 Sina Azadnajafabad
    right: This website is built with [Quarto](https://quarto.org/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/){target=_blank} {{< fa face-smile title="A smiling face" >}}



format:
  html:
    theme: 
      - flatly
      - mystyles.scss
    mainfont: Nunito
    toc: true
    page-layout: full
    include-after-body: 
      - altmetric-script.html # Include the Altmetric JavaScript Globally

editor: source

