project:
  type: website
  output-dir: docs

website:
  title: "SINA AZADNAJAFABAD"
  navbar:
    logo: media/Logo 1.png
    logo-alt: "Alt text for logo"
    
    right: # navigation bar location: accepts right/left/center
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
      - href: media/CV_Sina Azadnajafabad.pdf
        text: CV
        target: _blank # opens link (or page) in a new browser tab
  page-footer: 
    background: dark # or light
    left: Copyright 2024, Sina Azadnajafabad
    right: This website is built with [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank} {{< fa face-smile title="A smiling face" >}}



format:
  html:
    theme: mystyles.scss
    mainfont: Nunito
    toc: true
    page-layout: full

editor: visual

